lib/app/web/router.ex
defmodule App.Web.Router do
  use App.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/emails", Bamboo.EmailPreviewPlug
  end

  scope "/", App.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    post "/signin",   UserController, :signin
    post "/signout",  UserController, :signout
    post "/username", UserController, :username

    get "/write",       WriterController, :dashboard
    get "/write/:slug", WriterController, :write
    post "/write/new",  WriterController, :new_book
    post "/write/chp",  WriterController, :new_chapter
    post "/write/rch",  WriterController, :remove_chapter
    post "/write/upd",  WriterController, :update_draft
    post "/write/pbl",  WriterController, :update_text

    get "/:slug", ReaderController, :read
  end

  # Other scopes may use custom stacks.
  # scope "/api", App do
  #   pipe_through :api
  # end
end

lib/app/web/views/layout_view.ex
defmodule App.Web.LayoutView do
  use App.Web, :view

  def years do
    startYear   = 2017
    currentYear = DateTime.utc_now.year
    if currentYear == startYear do
      "#{currentYear}"
    else
      "#{startYear} - #{currentYear}"
    end
  end
end

lib/app/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render App.Web.LayoutView, "head.html", conn: @conn %>
  </head>

  <body>
    <%= render "header.html", conn: @conn, view_module: @view_module %>

    <div id='content-wrapper'>
      <div id='content'>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <%= render "footer.html" %>

    <script src='<%= static_path(@conn, "/js/app.js") %>'></script>
    <script>initializeAll()</script>
  </body>
</html>

lib/app/web/templates/layout/email.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <style>
      div#header {
        font-size: 18px;
        font-weight: bold;
        border-bottom: 1px solid #eee;
        padding-bottom: 8px;
      }
      div.content {
        margin-top: 32px;
      }
      div.link {
        display: inline-block;
        margin: 24px 12px 32px;
      }
      div.link a {
        padding: 12px 24px;
        border-radius: 50px;
        color: white;
        background-color: #29f;
        cursor: pointer;
        text-decoration: none;
      }
      div.link a:hover {
        background-color: #18e;
      }
      div.bare-link {
        display: inline;
        color: #222;
        word-wrap: break-word;
      }
      div.bare-link:hover {
        background-color: #eee;
      }
      div.small { font-size: 12px; color: #666; }
      div.small { font-size: 12px; color: #666; }
      div.footer {
        border-top: 1px solid #eee;
        padding-top: 12px;
        margin-top: 18px;
        color: #666;
      }
    </style>
  </head>

  <body>
    <div id='header'>
      <%= t "Nabookov" %>
    </div>
    <div id='content'>
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>

lib/app/web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>

lib/app/web/templates/layout/footer.html.eex
<footer>
  <div id='footer'>
    <div class='text-right text-small text-muted'>
      ©
      <%= t "nabookov.com" %>,
      <%= years %>
    </div>
  </div>
</footer>

lib/app/web/templates/layout/head.html.eex
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<meta name="csrf-token" content="<%= get_csrf_token() %>">

<title><%= t "nabookov" %></title>

<link href="https://fonts.googleapis.com/css?family=Merriweather|Roboto|PT+Sans|PT+Mono" rel="stylesheet">
<link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">

lib/app/web/templates/layout/header.html.eex
<%= unless signed_in?(@conn) do %>
  <%= render App.Web.ModalView, "signin.html" %>
  <%= render App.Web.ModalView, "signin_ok.html" %>

<% else %>
  <%= render App.Web.ModalView, "username.html", conn: @conn %>
  <%= if @view_module == App.Web.PageView and
         no_username?(current_user(@conn)) do %>
    <script>
      window.init_modal = '#username';
    </script>
  <% end %>
<% end %>

<header>
  <div id='header'>
    <div class='float-left'>
      <%= link to: page_path(@conn, :index), id: "header-logo", class: "link" do %>
        <span class='logo-thin'>na</span><span class='logo-thick'>book</span><span class='logo-thin'>ov</span>
      <% end %>
    </div>

    <div class='float-right'>
      <%= if signed_in?(@conn) do %>
        <%= unless @view_module == App.Web.WriterView do %>
          <%= link to: writer_path(@conn, :dashboard), id: "writer-mode", class: "link" do %>
            <%= t "Write" %>
          <% end %>
        <% end %>

        <div class='header-separator'></div>

        <div id='header-user' class='link'>
          <span class='name'>
            <%= username_or_email current_user(@conn) %>
          </span>

          <div class='dropdown invisible'>
            <div class='dropdown-item text-right'>
              <span class='link'
                    data-toggle='modal'
                    data-target='#username'>
                <%= t "Pen name" %>
              </span>
            </div>
            <div class='dropdown-item text-right'>
              <span id='signout' class='link'>
                <%= t "Sign out" %>
              </span>
            </div>
          </div>
        </div>

      <% else %>
        <span id='header-signin' class='link'
              data-toggle='modal'
              data-target='#signin'>
          <%= t "Sign up | Sign in" %>
        </span>
      <% end %>
    </div>
  </div>
</header>